 - https://www.statsmodels.org/dev/discretemod.html
 - https://www.statsmodels.org/dev/examples/notebooks/generated/discrete_choice_overview.html
 - https://www.statsmodels.org/dev/examples/notebooks/generated/discrete_choice_example.html

In [1]:
import numpy as np
import statsmodels.api as sm

In [2]:
spector_data = sm.datasets.spector.load(as_pandas=False)

In [3]:
spector_data.exog_name

['GPA', 'TUCE', 'PSI']

In [4]:
spector_data.exog[:5]

array([[ 2.66, 20.  ,  0.  ],
       [ 2.89, 22.  ,  0.  ],
       [ 3.28, 24.  ,  0.  ],
       [ 2.92, 12.  ,  0.  ],
       [ 4.  , 21.  ,  0.  ]])

In [5]:
spector_data.endog_name

'GRADE'

In [6]:
spector_data.endog[:5]

array([0., 0., 0., 0., 1.])

In [7]:
spector_data.exog = sm.add_constant(spector_data.exog, prepend=False)

In [10]:
spector_data.exog_name

['GPA', 'TUCE', 'PSI']

In [11]:
spector_data.exog[:5]

array([[ 2.66, 20.  ,  0.  ,  1.  ],
       [ 2.89, 22.  ,  0.  ,  1.  ],
       [ 3.28, 24.  ,  0.  ,  1.  ],
       [ 2.92, 12.  ,  0.  ,  1.  ],
       [ 4.  , 21.  ,  0.  ,  1.  ]])

In [13]:
lpm_mod = sm.OLS(spector_data.endog, spector_data.exog)

In [14]:
lpm_res = lpm_mod.fit()

In [18]:
lpm_mod

In [20]:
lpm_res.mse_model

1.0007586830809743

In [21]:
lpm_res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.416
Model:                            OLS   Adj. R-squared:                  0.353
Method:                 Least Squares   F-statistic:                     6.646
Date:                Wed, 13 Nov 2019   Prob (F-statistic):            0.00157
Time:                        08:19:47   Log-Likelihood:                -12.978
No. Observations:                  32   AIC:                             33.96
Df Residuals:                      28   BIC:                             39.82
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.4639      0.162      2.864      0.008       0.132       0.796
x2             0.0105      0.019      0.539      0.594      -0.029       0.050
x3             0.3786      0.139      2.720      0.011       0.093       0.664
const         -1.4980      0.524     -2.859      0.008      -2.571      -0.425
==============================================================================
Omnibus:                        0.176   Durbin-Watson:                   2.346
Prob(Omnibus):                  0.916   Jarque-Bera (JB):                0.167
Skew:                           0.141   Prob(JB):                        0.920
Kurtosis:                       2.786   Cond. No.                         176.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [26]:
lpm_res.predict(spector_data.exog)

array([-0.05426921,  0.07340692,  0.27529932, -0.01762875,  0.57778716,
        0.00701576, -0.03936941,  0.05363477,  0.16983152,  0.62464001,
       -0.06818476,  0.28335827,  0.39932119,  0.27651741,  0.41225249,
       -0.0276562 ,  0.03995305,  0.01409045,  0.56914272,  0.60868703,
        0.06696482,  0.85354417,  0.36800073,  0.78153024,  0.77445555,
        0.47660622,  0.63141194,  0.37090458,  0.79399386,  0.9773322 ,
        0.53887544,  0.1885505 ])