https://stackoverflow.com/questions/79071108/fit-a-3d-gaussian-using-sliced-2d-gaussian-distributions

In [1]:
import numpy as np
from scipy import stats, linalg

In [2]:
mu = np.array([1., 2., 3.])
sigma = np.array([
    [3., 0.5, -0.3],
    [0.5, 2., 0.8],
    [-0.3, 0.8, 1.]
])

In [3]:
law = stats.multivariate_normal(mean=mu, cov=sigma)

In [4]:
data = law.rvs(30_000)

In [5]:
stats.multivariate_normal.fit(data)

(array([0.97837063, 1.99128015, 2.99077697]),
 array([[ 2.99414584,  0.5167368 , -0.28805028],
        [ 0.5167368 ,  2.02233671,  0.81191272],
        [-0.28805028,  0.81191272,  1.01141398]]))

In [13]:
xm = data.mean(axis=0)

In [14]:
z = data - xm

In [15]:
C = z.T @ z

In [17]:
C / 30_000

array([[ 2.99414584,  0.5167368 , -0.28805028],
       [ 0.5167368 ,  2.02233671,  0.81191272],
       [-0.28805028,  0.81191272,  1.01141398]])