In [32]:
import numpy as np
import numdifftools as nd

 - https://stackoverflow.com/questions/79558153/python-function-for-propagation-of-uncertainty-with-covariance-terms
 - https://stackoverflow.com/questions/77956010/how-to-estimate-error-propagation-on-regressed-function-from-covariance-matrix-u/77964601#77964601
 - https://infoscience.epfl.ch/entities/publication/4a5b1a7e-d169-4f7f-97ad-f271b55ec91d

In [26]:
def model(x):
    return np.array([
        x[0] ** 2 * x[1] + x[0] * x[1] ** 3,
        x[0] * x[1] + x[0] ** 2 * x[1] ** 2,
        x[0] * x[1] ** 2 - x[0] * x[1] ** 4,
])

In [27]:
Cx = np.array([
    [+0.0150, -0.0025],
    [-0.0025, +0.0075],
])

In [28]:
x = np.array([1., 1.])

In [29]:
J = nd.Gradient(model)

In [30]:
Jx = J(x)
Jx

array([[ 3.,  4.],
       [ 3.,  3.],
       [ 0., -2.]])

In [31]:
Cf = Jx @ Cx @ Jx.T
Cf

array([[ 0.195 ,  0.1725, -0.045 ],
       [ 0.1725,  0.1575, -0.03  ],
       [-0.045 , -0.03  ,  0.03  ]])

In [35]:
sf = np.sqrt(np.diag(Cf))
sf

array([0.44158804, 0.3968627 , 0.17320508])