In [1]:
import numpy as np

In [4]:
A = np.array([[1, 1], [1, 0]], dtype="int32")
B = np.linalg.matrix_power(A, 46)
print(B, A.dtype)

[[-1323752223  1836311903]
 [ 1836311903  1134903170]] int32


In [3]:
A = np.array([[1, 1], [1, 0]], dtype="int64")
B = np.linalg.matrix_power(A, 46)
print(B, A.dtype)

[[2971215073 1836311903]
 [1836311903 1134903170]] int64


In [2]:
A = np.array([[1, 1], [1, 0]], dtype="float32")
B = np.linalg.matrix_power(A, 46)
print(B, A.dtype)

[[2.9712151e+09 1.8363119e+09]
 [1.8363119e+09 1.1349032e+09]] float32


In [1]:
A = np.array([[1, 1], [1, 0]], dtype="float64")
B = np.linalg.matrix_power(A, 46)
print(B, A.dtype)

[[2.97121507e+09 1.83631190e+09]
 [1.83631190e+09 1.13490317e+09]] float64


In [5]:
A = np.array([[1, 1], [1, 0]], dtype=object)
B = np.linalg.matrix_power(A, 46)
print(B, A.dtype)

[[2971215073 1836311903]
 [1836311903 1134903170]] object


In [7]:
A = np.array([[1, 1], [1, 0]], dtype=object)
B = np.linalg.matrix_power(A, 100)
print(B, A.dtype)

[[573147844013817084101 354224848179261915075]
 [354224848179261915075 218922995834555169026]] object
