https://stackoverflow.com/questions/73814378/scipy-curve-fit-incorrect-for-large-x-values

In [1]:
import numpy as np
import scipy.optimize

y = np.arange(5)
x = 1e10 + y

In [2]:
x.dtype

dtype('float64')

In [3]:
np.finfo(np.float64).precision

15

In [4]:
def fit_func(x, a, b):
    return a + b * x


result = scipy.optimize.curve_fit(fit_func, x, y, p0=[-x[0], 0.0])
result

/usr/local/lib/python3.6/dist-packages/scipy/optimize/minpack.py:829: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)


(array([-1.e+10,  1.e+00]),
 array([[inf, inf],
        [inf, inf]]))

In [5]:
x/1e9

array([10., 10., 10., 10., 10.])

In [6]:
xm = np.mean(x)
xs = np.std(x)

In [7]:
xm

10000000002.0

In [8]:
xs

1.4142135623730951

In [9]:
result = scipy.optimize.curve_fit(fit_func, (x - xm)/xs, y)
result

(array([2.        , 1.41421356]),
 array([[0., 0.],
        [0., 0.]]))

In [10]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LinearRegression

In [11]:
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("regressor", LinearRegression())
])

In [12]:
pipe.fit(x.reshape(-1, 1), y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('regressor', LinearRegression())])

In [13]:
pipe.named_steps["regressor"].coef_

array([1.41421356])

In [14]:
pipe.named_steps["regressor"].coef_
pipe.named_steps["regressor"].intercept_

2.0

In [15]:
pipe.named_steps["scaler"].mean_

array([1.e+10])

In [16]:
pipe.named_steps["scaler"].scale_

array([1.41421356])

In [17]:
1.41421356*1.41421356

1.9999999932878738

In [18]:
a = result[0][1]/xs   # 1.0
a

1.0

In [19]:
b = result[0][0] - xm*result[0][1]/xs  # -1000000000.0
b

-10000000000.0

In [20]:
from scipy import stats

In [21]:
stats.linregress(x, y)

LinregressResult(slope=1.0, intercept=-10000000000.0, rvalue=1.0, pvalue=1.2004217548761408e-30, stderr=0.0)