https://stackoverflow.com/questions/73814378/scipy-curve-fit-incorrect-for-large-x-values

In [1]:
import numpy as np
import scipy.optimize

y = np.arange(5)
x = 1e9 + y

In [2]:
def fit_func(x, a, b):
    return a + b * x


result = scipy.optimize.curve_fit(fit_func, x, y, p0=[-x[0], 0.0])
result

/usr/local/lib/python3.6/dist-packages/scipy/optimize/minpack.py:829: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)


(array([-4.53788811e+08,  4.53788812e-01]),
 array([[inf, inf],
        [inf, inf]]))

In [3]:
x/1e9

array([1., 1., 1., 1., 1.])

In [4]:
xm = np.mean(x)
xs = np.std(x)

In [5]:
xm

1000000002.0

In [6]:
xs

1.4142135623730951

In [7]:
result = scipy.optimize.curve_fit(fit_func, (x - xm)/xs, y)
result

(array([2.        , 1.41421356]),
 array([[0., 0.],
        [0., 0.]]))

In [8]:
scipy.optimize.curve_fit(fit_func, x-1e9, y, p0=[-x[0], 0.0])

(array([7.14978086e-24, 1.00000000e+00]),
 array([[ 1.19293406e-23, -0.00000000e+00],
        [ 0.00000000e+00,  3.97644687e-25]]))

In [9]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LinearRegression

In [10]:
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("regressor", LinearRegression())
])

In [11]:
pipe.fit(x.reshape(-1, 1), y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('regressor', LinearRegression())])

In [12]:
pipe.named_steps["regressor"].coef_

array([1.41421356])

In [13]:
pipe.named_steps["regressor"].coef_
pipe.named_steps["regressor"].intercept_

2.0

In [14]:
pipe.named_steps["scaler"].mean_

array([1.e+09])

In [15]:
pipe.named_steps["scaler"].scale_

array([1.41421356])

In [16]:
dir(pipe.named_steps["scaler"])

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_check_n_features',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_reset',
 '_validate_data',
 'copy',
 'fit',
 'fit_transform',
 'get_params',
 'inverse_transform',
 'mean_',
 'n_features_in_',
 'n_samples_seen_',
 'partial_fit',
 'scale_',
 'set_params',
 'transform',
 'var_',
 'with_mean',
 'with_std']

In [17]:
1.41421356*1.41421356

1.9999999932878738

In [22]:
a = result[0][1]/xs   # 1.0
a

1.0

In [25]:
b = result[0][0] - xm*result[0][1]/xs  # -1000000000.0
b

-1000000000.0