In [1]:
import numpy as np
#import scipy
from scipy import linalg

- https://stackoverflow.com/questions/64218559/simple-linear-dependency
- https://en.wikipedia.org/wiki/Linear_independence
- https://en.wikipedia.org/wiki/LU_decomposition
- https://en.wikipedia.org/wiki/Gaussian_elimination


In [2]:
v1 = np.array([0, 5, 0])
v2 = np.array([0, -10, 0])
v3 = np.array([1, 2, 3])
v4 = np.array([-2, -4, -6])

In [3]:
p, l, u = linalg.lu(np.array([v1, v3]).T)
p, l, u

(array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[1.        , 0.        ],
        [0.        , 1.        ],
        [0.        , 0.33333333]]),
 array([[5., 2.],
        [0., 3.]]))

In [4]:
np.linalg.matrix_rank(np.array([v1, v2]).T)

1

In [5]:
np.linalg.matrix_rank(np.array([v1, v3]).T)

2

In [6]:
np.cross(v1, v2)

array([0, 0, 0])

In [7]:
np.cross(v1, v3)

array([15,  0, -5])

In [8]:
U, s, V = linalg.svd(np.array([v1, v2]).T)
s

array([11.18033989,  0.        ])

In [9]:
U, s, V = linalg.svd(np.array([v1, v3]).T)
s

array([5.55992016, 2.84381571])

In [10]:
def indep1(*args):
    A = np.array(args).T
    return np.linalg.matrix_rank(A) == len(args)

In [11]:
indep1(v1, v2, v3)

False

In [12]:
def indep2(a, b):
    return not np.allclose(np.cross(a, b), 0.)

In [13]:
indep2(v1, v2)
indep2(v1, v3)
#indep2(v1, v2, v3)

True

In [15]:
np.linalg.solve(np.array([v1, v2, v3]).T, np.zeros(v1.size))

LinAlgError: Singular matrix

In [49]:
def indep3(a, b):
    r = a/b
    q = np.isfinite(r)
    return not np.allclose(r[q], r[q][0])
    #return np.allclose(r, r[0])

In [50]:
indep3(v1, v2)
indep3(v1, v3)
#indep3(v3, v4)
#indep3(v3, np.zeros(v1.size)) # IndexError

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


True

In [42]:
indep1(v1, np.zeros(v1.size))

False

In [43]:
indep2(v1, np.zeros(v1.size))

False