In [12]:
import numpy as np
from scipy import linalg

- https://stackoverflow.com/questions/64218559/simple-linear-dependency
- https://en.wikipedia.org/wiki/Linear_independence
- https://en.wikipedia.org/wiki/LU_decomposition
- https://en.wikipedia.org/wiki/Gaussian_elimination


In [35]:
v1 = np.array([0, 5, 0])
v2 = np.array([0, -10, 0])
v3 = np.array([1, 2, 3])
v4 = np.array([-2, -4, -6])

In [44]:
p, l, u = scipy.linalg.lu(np.array([v1, v3]).T)
p, l, u

(array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[1.        , 0.        ],
        [0.        , 1.        ],
        [0.        , 0.33333333]]),
 array([[5., 2.],
        [0., 3.]]))

In [41]:
np.linalg.matrix_rank(np.array([v1, v2]).T)

1

In [42]:
np.linalg.matrix_rank(np.array([v1, v3]).T)

2

In [45]:
np.cross(v1, v2)

array([0, 0, 0])

In [46]:
np.cross(v1, v3)

array([15,  0, -5])

In [52]:
U, s, V = linalg.svd(np.array([v1, v2]).T)
s

array([11.18033989,  0.        ])

In [54]:
U, s, V = linalg.svd(np.array([v1, v3]).T)
s

array([5.55992016, 2.84381571])

In [56]:
np.linalg.solve(np.array([v1]), v2)

LinAlgError: Last 2 dimensions of the array must be square

In [57]:
def indep1(*args):
    A = np.array(args).T
    return np.linalg.matrix_rank(A) == len(args)

In [60]:
indep1(v1, v2, v3)

False

In [63]:
def indep2(a, b):
    return not np.allclose(np.cross(a, b), 0.)

In [69]:
indep2(v1, v2)
indep2(v1, v3)
indep2(v1, v2, v3)

TypeError: indep2() takes 2 positional arguments but 3 were given