In [6]:
import numpy as np
from scipy.optimize import least_squares
import matplotlib.pyplot as plt

def func(x, para):
    return ((para[0] ** 2) * x) + (para[1] / x) + (para[2] * x)

def func(x, p):
    return p[0]  * x **2 + p[1] * x + p[2]

def res(para, x_d, y_d):
    return y_d - func(x_d, para)
    
x_d = np.array([1, 2, 3, 4, 5])
y_d = np.array([2, 4, 9, 16, 25])

initial_paras = [1, 1, 1]

result = least_squares(res, initial_paras, args=(x_d, y_d))
result

     message: `xtol` termination condition is satisfied.
     success: True
      status: 3
         fun: [ 1.143e-01 -2.571e-01  8.571e-02  1.429e-01 -8.571e-02]
           x: [ 1.143e+00 -1.057e+00  1.800e+00]
        cost: 0.0571428571428573
         jac: [[-1.000e+00 -1.000e+00 -1.000e+00]
               [-4.000e+00 -2.000e+00 -1.000e+00]
               ...
               [-1.600e+01 -4.000e+00 -1.000e+00]
               [-2.500e+01 -5.000e+00 -1.000e+00]]
        grad: [ 8.941e-09  1.611e-09  1.608e-08]
  optimality: 1.6083786736995895e-08
 active_mask: [ 0.000e+00  0.000e+00  0.000e+00]
        nfev: 5
        njev: 4