In [1]:
import numpy as np
import scipy as sp
from scipy.special import expit, logit
import scipy.optimize

https://stackoverflow.com/questions/57615235/scipy-optimize-raises-valueerror-despite-x0-being-within-bounds

In [15]:
def f(x,x0,g,c,k):
    y = c*expit(k*10.*(x-x0)) + g*1e-19*(1.-c)
    return y

In [16]:
#               x0                      g                       c                       k
p0 = np.array([8.841357069490852e-01, 4.492363462957287, 5.547073496706608e-01, 7.435378446218519e+00])
bounds = np.array([[-1.,1.], [0.,10.], [0.,1.], [0.,20.]])
x = np.array([1.0, 1.0, 1.0, 1.0, 1.0, 0.8911796599834791, 1.0, 1.0, 1.0, 0.33232919909076103, 1.0])
y = np.array([0.999, 0.999, 0.999, 0.999, 0.999, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001])
s = np.array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9])


In [17]:

print([pval >= b[0] and pval <= b[1] for pval,b in zip(p0,bounds)])

[True, True, True, True]


In [18]:

fit,cov = sp.optimize.curve_fit(f,x,y,p0=p0,sigma=s,bounds=([b[0] for b in bounds],[b[1] for b in bounds]),method='dogbox',tr_solver='exact')

print(fit)
print(cov)

[ 0.93562     4.4932589   0.55550743 14.11561844]
[[ 3.01319703e+13 -5.31967224e+08  6.53913058e+11 -9.56817702e+15]
 [-5.31967224e+08  9.39165693e+03 -1.15445592e+07  1.68922129e+11]
 [ 6.53913058e+11 -1.15445592e+07  1.41909833e+10 -2.07645097e+14]
 [-9.56817702e+15  1.68922129e+11 -2.07645097e+14  3.03830153e+18]]


In [6]:
np.__version__

'1.23.3'

In [7]:
sp.__version__

'1.9.3'